# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'medico.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Medico_MainWindow(object):
    def setupUi(self, Medico_MainWindow):
        Medico_MainWindow.setObjectName("Medico_MainWindow")
        Medico_MainWindow.resize(851, 623)
        Medico_MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.58, x2:1, y2:0.551, stop:0.857955 rgba(227, 227, 227, 255), stop:1 rgba(255, 255, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(Medico_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Btn_Agenda_m = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Agenda_m.setGeometry(QtCore.QRect(30, 140, 231, 161))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setPointSize(13)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.Btn_Agenda_m.setFont(font)
        self.Btn_Agenda_m.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.Btn_Agenda_m.setObjectName("Btn_Agenda_m")
        self.Btn_agregarcita_m = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_agregarcita_m.setGeometry(QtCore.QRect(280, 140, 231, 161))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setPointSize(13)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.Btn_agregarcita_m.setFont(font)
        self.Btn_agregarcita_m.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.Btn_agregarcita_m.setObjectName("Btn_agregarcita_m")
        self.Btn_nuevopaciente_m = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_nuevopaciente_m.setGeometry(QtCore.QRect(530, 140, 241, 161))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setPointSize(13)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.Btn_nuevopaciente_m.setFont(font)
        self.Btn_nuevopaciente_m.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.Btn_nuevopaciente_m.setObjectName("Btn_nuevopaciente_m")
        self.btn_config_m = QtWidgets.QPushButton(self.centralwidget)
        self.btn_config_m.setGeometry(QtCore.QRect(530, 330, 241, 151))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setPointSize(13)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.btn_config_m.setFont(font)
        self.btn_config_m.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.btn_config_m.setObjectName("btn_config_m")
        self.btn_historialclinico_m = QtWidgets.QPushButton(self.centralwidget)
        self.btn_historialclinico_m.setGeometry(QtCore.QRect(30, 330, 231, 151))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setPointSize(13)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.btn_historialclinico_m.setFont(font)
        self.btn_historialclinico_m.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.btn_historialclinico_m.setObjectName("btn_historialclinico_m")
        self.Btn_buscarpaciente_m = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_buscarpaciente_m.setGeometry(QtCore.QRect(280, 330, 231, 151))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setPointSize(13)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.Btn_buscarpaciente_m.setFont(font)
        self.Btn_buscarpaciente_m.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.Btn_buscarpaciente_m.setObjectName("Btn_buscarpaciente_m")
        self.label_medico = QtWidgets.QLabel(self.centralwidget)
        self.label_medico.setGeometry(QtCore.QRect(320, 40, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_medico.setFont(font)
        self.label_medico.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.label_medico.setObjectName("label_medico")
        Medico_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Medico_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 851, 21))
        self.menubar.setObjectName("menubar")
        Medico_MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Medico_MainWindow)
        self.statusbar.setObjectName("statusbar")
        Medico_MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(Medico_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(Medico_MainWindow)

    def retranslateUi(self, Medico_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        Medico_MainWindow.setWindowTitle(_translate("Medico_MainWindow", "Médico"))
        self.Btn_Agenda_m.setText(_translate("Medico_MainWindow", "AGENDA"))
        self.Btn_agregarcita_m.setText(_translate("Medico_MainWindow", "AGREGAR CITA"))
        self.Btn_nuevopaciente_m.setText(_translate("Medico_MainWindow", "NUEVO PACIENTE"))
        self.btn_config_m.setText(_translate("Medico_MainWindow", "CONFIGURACION"))
        self.btn_historialclinico_m.setText(_translate("Medico_MainWindow", "HISTORIAL CLÍNICO"))
        self.Btn_buscarpaciente_m.setText(_translate("Medico_MainWindow", "BUSCAR PACIENTE"))
        self.label_medico.setText(_translate("Medico_MainWindow", "MÉDICO"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Medico_MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Medico_MainWindow()
    ui.setupUi(Medico_MainWindow)
    Medico_MainWindow.show()
    sys.exit(app.exec_())
